export const LOGIN = "LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";

export const ADD_INTEREST = "ADD_INTEREST";
export const ADD_INTEREST_SUCCESS = "ADD_INTEREST_SUCCESS";
export const REMOVE_INTEREST_SUCCESS = "REMOVE_INTEREST_SUCCESS";
export const REMOVE_INTERESTS_SUCCESS = "REMOVE_INTERESTS_SUCCESS";

export const GET_NEAR_USERS_SUCCESS = "GET_NEAR_USERS_SUCCESS";
